# Generated by Django 5.2.1 on 2025-06-04 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breach',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('breach_date', models.DateField(blank=True, null=True)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('data_classes', models.JSONField(default=list)),
                ('is_verified', models.BooleanField(default=True)),
                ('is_fabricated', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_retired', models.BooleanField(default=False)),
                ('is_spam_list', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filtración',
                'verbose_name_plural': 'Filtraciones',
                'indexes': [models.Index(fields=['name'], name='core_breach_name_91bf0a_idx'), models.Index(fields=['domain'], name='core_breach_domain_98adb2_idx'), models.Index(fields=['breach_date'], name='core_breach_breach__6da8a0_idx'), models.Index(fields=['is_sensitive'], name='core_breach_is_sens_f572cd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('processing', 'Procesando'), ('completed', 'Completada'), ('failed', 'Fallida')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('breaches', models.ManyToManyField(blank=True, to='core.breach')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verificación',
                'verbose_name_plural': 'Verificaciones',
                'indexes': [models.Index(fields=['email'], name='core_verifi_email_0861df_idx'), models.Index(fields=['status'], name='core_verifi_status_954b01_idx'), models.Index(fields=['created_at'], name='core_verifi_created_7bc098_idx')],
            },
        ),
    ]
