# Generated by Django 4.2.7 on 2025-06-05 07:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Categoría de Blog',
                'verbose_name_plural': 'Categorías de Blog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('category', models.CharField(choices=[('vpn', 'VPN'), ('antivirus', 'Antivirus'), ('password', 'Gestores de Contraseñas'), ('encryption', 'Encriptación'), ('firewall', 'Firewalls'), ('other', 'Otras')], default='other', max_length=20, verbose_name='Categoría')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('url', models.URLField(verbose_name='URL')),
                ('affiliate_url', models.URLField(blank=True, null=True, verbose_name='URL de Afiliado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tools/', verbose_name='Imagen')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Valoración (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Extracto')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Imagen Destacada')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.blogcategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Artículo de Blog',
                'verbose_name_plural': 'Artículos de Blog',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
