# Generated by Django 5.2.2 on 2025-06-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogcategory_tool_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='breach',
            name='pwn_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
